service: PokemonAPI-POST
provider:
  name: aws
  runtime: python 3.9
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-0e94dc76d54a58dea
    subnetIds:
      - subnet-08e004b9bb88d8b4d
      - subnet-0b8c05bfa50f63437
      - subnet-08b179f2fb43c6244
      - subnet-0c0608f1ce8f52a9e
      - subnet-0f7dd66fc1fd2fb00
      - subnet-0703d33f3a409cf69
functions:
  my-lambda-function:
    handler: lambda_function.lambda_handler
    environmnet:
      DB_HOST: db-pokemones.c1293ggfy4kr.eu-north-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: database-1
      DB_USER: tansoto
      DB_PASSWORD: 123456789
    events:
      - htpp:
          path: /post
          method: POST
